assets:
  - js
  - css/main.css
model:
  articles: "@data/articles"
files:
  /:
    view: home.html
    model:
      valueForHome: valueForHome!
  /articles/{{file}}.html:
    view: article.html
    model:
      valueForArticles: valueForArticles!
    fileModels: "data/articles"


